[tox]
envlist = py39,py310,py311,py312,py313,py314

[testenv]
deps = .[tests]
commands = pytest {posargs}

[testenv:e2e]
passenv = KEY, PROXY_URL
deps = .[tests]
commands = pytest -m e2e --override-ini="addopts=" {posargs}
